version: '3'

services:
  db:
    image: postgres:9.6-alpine
    ports:
      - 55432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hzl_production
    volumes:
      - postgres:/var/lib/postgresql/data
      - postgres-run:/var/run/postgresql
    restart: always
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
        #HZL_UID: 1000
        #HZL_GID: 1000
    image: houzel:latest
    depends_on:
      - db
    volumes:
      - ./config/houzel.yml:/houzel/config/houzel.yml:ro
      - ./config/database.yml:/houzel/config/database.yml:ro
    ports:
      - 3000:3000
    restart: always

volumes:
  postgres:
  postgres-run:
